sudo: required

services:
    - docker

before_install:
    - docker build -t banuaraidi/loginapp .

script:
    - docker run banuaraidi/loginapp npm test

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push banuaraidi/loginapp

deploy:
    provider: elasticbeanstalk
    region: ap-southeast-1
    app: docker-loginapp
    env: DockerLoginapp-env
    bucket_name: elasticbeanstalk-ap-southeast-1-040596896543
    bucket_path: docker-loginapp
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_acces_key: $AWS_SECRET_KEY
